// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.24.3
// source: stress.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Agent 状态枚举 | EN Agent state enumeration
// 定义压测代理（Slave）的运行状态 | EN Define the running state of stress test agent (Slave)
type AgentState int32

const (
	AgentState_AGENT_STATE_UNSPECIFIED AgentState = 0 // 未指定状态（proto3 要求第一个值为 0） | EN Unspecified state (proto3 requires the first value to be 0)
	AgentState_AGENT_STATE_IDLE        AgentState = 1 // 空闲状态：代理已就绪，等待接收任务 | EN Idle state: Agent is ready and waiting to receive tasks
	AgentState_AGENT_STATE_RUNNING     AgentState = 2 // 运行中：代理正在执行压测任务 | EN Running: Agent is executing stress test tasks
	AgentState_AGENT_STATE_STOPPING    AgentState = 3 // 停止中：代理正在停止当前任务 | EN Stopping: Agent is stopping the current task
	AgentState_AGENT_STATE_ERROR       AgentState = 4 // 错误状态：代理运行出错，无法正常工作 | EN Error: Agent encountered an error and cannot work normally
	AgentState_AGENT_STATE_OFFLINE     AgentState = 5 // 离线状态：代理与主节点失联 | EN Offline: Agent lost connection with master node
)

// Enum value maps for AgentState.
var (
	AgentState_name = map[int32]string{
		0: "AGENT_STATE_UNSPECIFIED",
		1: "AGENT_STATE_IDLE",
		2: "AGENT_STATE_RUNNING",
		3: "AGENT_STATE_STOPPING",
		4: "AGENT_STATE_ERROR",
		5: "AGENT_STATE_OFFLINE",
	}
	AgentState_value = map[string]int32{
		"AGENT_STATE_UNSPECIFIED": 0,
		"AGENT_STATE_IDLE":        1,
		"AGENT_STATE_RUNNING":     2,
		"AGENT_STATE_STOPPING":    3,
		"AGENT_STATE_ERROR":       4,
		"AGENT_STATE_OFFLINE":     5,
	}
)

func (x AgentState) Enum() *AgentState {
	p := new(AgentState)
	*p = x
	return p
}

func (x AgentState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentState) Descriptor() protoreflect.EnumDescriptor {
	return file_stress_proto_enumTypes[0].Descriptor()
}

func (AgentState) Type() protoreflect.EnumType {
	return &file_stress_proto_enumTypes[0]
}

func (x AgentState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentState.Descriptor instead.
func (AgentState) EnumDescriptor() ([]byte, []int) {
	return file_stress_proto_rawDescGZIP(), []int{0}
}

// 任务状态枚举 | EN Task state enumeration
// 定义压测任务的生命周期状态 | EN Define the lifecycle state of stress test tasks
type TaskState int32

const (
	TaskState_TASK_STATE_UNSPECIFIED TaskState = 0 // 未指定状态 | EN Unspecified state
	TaskState_TASK_STATE_PENDING     TaskState = 1 // 待执行：任务已下发，等待代理开始执行 | EN Pending: Task has been issued, waiting for agent to start execution
	TaskState_TASK_STATE_RUNNING     TaskState = 2 // 运行中：任务正在执行 | EN Running: Task is being executed
	TaskState_TASK_STATE_COMPLETED   TaskState = 3 // 已完成：任务正常执行完毕 | EN Completed: Task finished execution normally
	TaskState_TASK_STATE_FAILED      TaskState = 4 // 执行失败：任务执行过程中出错 | EN Failed: Task encountered an error during execution
	TaskState_TASK_STATE_STOPPED     TaskState = 5 // 已停止：任务被手动停止 | EN Stopped: Task was manually stopped
)

// Enum value maps for TaskState.
var (
	TaskState_name = map[int32]string{
		0: "TASK_STATE_UNSPECIFIED",
		1: "TASK_STATE_PENDING",
		2: "TASK_STATE_RUNNING",
		3: "TASK_STATE_COMPLETED",
		4: "TASK_STATE_FAILED",
		5: "TASK_STATE_STOPPED",
	}
	TaskState_value = map[string]int32{
		"TASK_STATE_UNSPECIFIED": 0,
		"TASK_STATE_PENDING":     1,
		"TASK_STATE_RUNNING":     2,
		"TASK_STATE_COMPLETED":   3,
		"TASK_STATE_FAILED":      4,
		"TASK_STATE_STOPPED":     5,
	}
)

func (x TaskState) Enum() *TaskState {
	p := new(TaskState)
	*p = x
	return p
}

func (x TaskState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskState) Descriptor() protoreflect.EnumDescriptor {
	return file_stress_proto_enumTypes[1].Descriptor()
}

func (TaskState) Type() protoreflect.EnumType {
	return &file_stress_proto_enumTypes[1]
}

func (x TaskState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskState.Descriptor instead.
func (TaskState) EnumDescriptor() ([]byte, []int) {
	return file_stress_proto_rawDescGZIP(), []int{1}
}

// 协议类型枚举 | EN Protocol type enumeration
// 定义压测支持的协议类型 | EN Define the protocol types supported by stress testing
type Protocol int32

const (
	Protocol_PROTOCOL_UNSPECIFIED Protocol = 0 // 未指定协议 | EN Unspecified protocol
	Protocol_PROTOCOL_HTTP        Protocol = 1 // HTTP/HTTPS 协议 | EN HTTP/HTTPS protocol
	Protocol_PROTOCOL_GRPC        Protocol = 2 // gRPC 协议 | EN gRPC protocol
	Protocol_PROTOCOL_WEBSOCKET   Protocol = 3 // WebSocket 协议 | EN WebSocket protocol
)

// Enum value maps for Protocol.
var (
	Protocol_name = map[int32]string{
		0: "PROTOCOL_UNSPECIFIED",
		1: "PROTOCOL_HTTP",
		2: "PROTOCOL_GRPC",
		3: "PROTOCOL_WEBSOCKET",
	}
	Protocol_value = map[string]int32{
		"PROTOCOL_UNSPECIFIED": 0,
		"PROTOCOL_HTTP":        1,
		"PROTOCOL_GRPC":        2,
		"PROTOCOL_WEBSOCKET":   3,
	}
)

func (x Protocol) Enum() *Protocol {
	p := new(Protocol)
	*p = x
	return p
}

func (x Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_stress_proto_enumTypes[2].Descriptor()
}

func (Protocol) Type() protoreflect.EnumType {
	return &file_stress_proto_enumTypes[2]
}

func (x Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol.Descriptor instead.
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return file_stress_proto_rawDescGZIP(), []int{2}
}

// Slave 信息 | EN Slave Information
// 从节点注册时上报的自身基础信息 | EN Basic information reported by slave node during registration
type SlaveInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlaveId       string                 `protobuf:"bytes,1,opt,name=slave_id,json=slaveId,proto3" json:"slave_id,omitempty"`                                                          // 从节点唯一标识（可由主节点分配或自身生成） | EN Unique identifier of slave node (can be assigned by master or generated by itself)
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`                                                                       // 从节点主机名 | EN Hostname of slave node
	Ip            string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`                                                                                   // 从节点 IP 地址 | EN IP address of slave node
	CpuCores      int32                  `protobuf:"varint,4,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`                                                      // CPU 核心数（用于主节点调度任务） | EN Number of CPU cores (used by master node for task scheduling)
	Memory        int64                  `protobuf:"varint,5,opt,name=memory,proto3" json:"memory,omitempty"`                                                                          // 内存大小（字节） | EN Memory size (bytes)
	Version       string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`                                                                         // 从节点程序版本号 | EN Version number of slave node program
	Region        string                 `protobuf:"bytes,7,opt,name=region,proto3" json:"region,omitempty"`                                                                           // 节点所在区域（如机房/地域，用于分组调度） | EN Node region (e.g., computer room/region, used for group scheduling)
	Labels        map[string]string      `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 自定义标签（用于筛选/分组） | EN Custom labels (used for filtering/grouping)
	GrpcPort      int32                  `protobuf:"varint,9,opt,name=grpc_port,json=grpcPort,proto3" json:"grpc_port,omitempty"`                                                      // gRPC 服务端口（主节点调用从节点的端口） | EN gRPC service port (port for master node to call slave node)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlaveInfo) Reset() {
	*x = SlaveInfo{}
	mi := &file_stress_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlaveInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlaveInfo) ProtoMessage() {}

func (x *SlaveInfo) ProtoReflect() protoreflect.Message {
	mi := &file_stress_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlaveInfo.ProtoReflect.Descriptor instead.
func (*SlaveInfo) Descriptor() ([]byte, []int) {
	return file_stress_proto_rawDescGZIP(), []int{0}
}

func (x *SlaveInfo) GetSlaveId() string {
	if x != nil {
		return x.SlaveId
	}
	return ""
}

func (x *SlaveInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *SlaveInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *SlaveInfo) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *SlaveInfo) GetMemory() int64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *SlaveInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SlaveInfo) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *SlaveInfo) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *SlaveInfo) GetGrpcPort() int32 {
	if x != nil {
		return x.GrpcPort
	}
	return 0
}

// 注册响应 | EN Registration Response
// 主节点对从节点注册请求的响应 | EN Master node's response to slave node registration request
type RegisterResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                              // 注册是否成功 | EN Whether registration is successful
	Message           string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                               // 注册结果描述（失败时返回原因） | EN Description of registration result (returns reason if failed)
	Token             string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`                                                   // 身份令牌（后续心跳/上报需携带，用于鉴权） | EN Identity token (required for subsequent heartbeat/reporting for authentication)
	HeartbeatInterval int64                  `protobuf:"varint,4,opt,name=heartbeat_interval,json=heartbeatInterval,proto3" json:"heartbeat_interval,omitempty"` // 心跳间隔（秒）：主节点指定从节点的心跳发送频率 | EN Heartbeat interval (seconds): Master node specifies the heartbeat sending frequency of slave node
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_stress_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stress_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_stress_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterResponse) GetHeartbeatInterval() int64 {
	if x != nil {
		return x.HeartbeatInterval
	}
	return 0
}

// 心跳请求 | EN Heartbeat Request
// 从节点向主节点发送心跳的请求参数 | EN Request parameters for slave node to send heartbeat to master node
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlaveId       string                 `protobuf:"bytes,1,opt,name=slave_id,json=slaveId,proto3" json:"slave_id,omitempty"` // 从节点 ID | EN Slave node ID
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`           // 心跳发送时间戳（毫秒） | EN Heartbeat sending timestamp (milliseconds)
	Status        *SlaveStatus           `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                  // 从节点当前状态详情 | EN Detailed current status of slave node
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_stress_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stress_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_stress_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetSlaveId() string {
	if x != nil {
		return x.SlaveId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatRequest) GetStatus() *SlaveStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// 心跳响应 | EN Heartbeat Response
// 主节点对心跳请求的响应 | EN Master node's response to heartbeat request
type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`            // 心跳是否被正常接收 | EN Whether heartbeat is received normally
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`   // 响应描述信息 | EN Response description information
	Commands      []string               `protobuf:"bytes,3,rep,name=commands,proto3" json:"commands,omitempty"` // 主节点下发的指令列表（如"重启"、"更新配置"等） | EN List of commands issued by master node (e.g., "restart", "update config", etc.)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_stress_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stress_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_stress_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HeartbeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HeartbeatResponse) GetCommands() []string {
	if x != nil {
		return x.Commands
	}
	return nil
}

// 任务配置 | EN Task Configuration
// 主节点下发给从节点的压测任务详细配置 | EN Detailed configuration of stress test task sent by master node to slave node
type TaskConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                          // 任务唯一标识 | EN Unique task identifier
	Protocol       Protocol               `protobuf:"varint,2,opt,name=protocol,proto3,enum=stress.Protocol" json:"protocol,omitempty"`              // 压测协议类型（http/grpc/websocket） | EN Stress test protocol type (http/grpc/websocket)
	Target         string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`                                        // 压测目标地址（如 http://127.0.0.1:8080/api） | EN Stress test target address (e.g., http://127.0.0.1:8080/api)
	WorkerCount    int32                  `protobuf:"varint,4,opt,name=worker_count,json=workerCount,proto3" json:"worker_count,omitempty"`          // 并发工作协程数（压测并发数） | EN Number of concurrent worker goroutines (stress test concurrency)
	Duration       int32                  `protobuf:"varint,5,opt,name=duration,proto3" json:"duration,omitempty"`                                   // 压测持续时间（秒） | EN Stress test duration (seconds)
	RampUp         int32                  `protobuf:"varint,6,opt,name=ramp_up,json=rampUp,proto3" json:"ramp_up,omitempty"`                         // 预热时间（秒）：逐步提升并发数的时间 | EN Ramp-up time (seconds): Time to gradually increase concurrency
	ConfigData     []byte                 `protobuf:"bytes,7,opt,name=config_data,json=configData,proto3" json:"config_data,omitempty"`              // 详细配置数据（JSON 序列化后的字节数据，如请求头、请求体等） | EN Detailed configuration data (JSON serialized bytes, e.g., request headers, request body, etc.)
	ReportInterval int32                  `protobuf:"varint,8,opt,name=report_interval,json=reportInterval,proto3" json:"report_interval,omitempty"` // 统计数据上报间隔（秒） | EN Statistics reporting interval (seconds)
	State          TaskState              `protobuf:"varint,9,opt,name=state,proto3,enum=stress.TaskState" json:"state,omitempty"`                   // 任务初始状态 | EN Initial task state
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaskConfig) Reset() {
	*x = TaskConfig{}
	mi := &file_stress_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskConfig) ProtoMessage() {}

func (x *TaskConfig) ProtoReflect() protoreflect.Message {
	mi := &file_stress_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskConfig.ProtoReflect.Descriptor instead.
func (*TaskConfig) Descriptor() ([]byte, []int) {
	return file_stress_proto_rawDescGZIP(), []int{4}
}

func (x *TaskConfig) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskConfig) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

func (x *TaskConfig) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *TaskConfig) GetWorkerCount() int32 {
	if x != nil {
		return x.WorkerCount
	}
	return 0
}

func (x *TaskConfig) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *TaskConfig) GetRampUp() int32 {
	if x != nil {
		return x.RampUp
	}
	return 0
}

func (x *TaskConfig) GetConfigData() []byte {
	if x != nil {
		return x.ConfigData
	}
	return nil
}

func (x *TaskConfig) GetReportInterval() int32 {
	if x != nil {
		return x.ReportInterval
	}
	return 0
}

func (x *TaskConfig) GetState() TaskState {
	if x != nil {
		return x.State
	}
	return TaskState_TASK_STATE_UNSPECIFIED
}

// 任务响应 | EN Task Response
// 从节点对执行任务请求的响应 | EN Slave node's response to task execution request
type TaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`          // 是否接受任务（如资源不足时可拒绝） | EN Whether to accept the task (can be rejected if resources are insufficient)
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`             // 响应描述（拒绝时说明原因） | EN Response description (explain reason if rejected)
	TaskId        string                 `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // 任务 ID（确认接收的任务标识） | EN Task ID (identifier of confirmed received task)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_stress_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stress_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_stress_proto_rawDescGZIP(), []int{5}
}

func (x *TaskResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *TaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// 停止请求 | EN Stop Request
// 主节点向从节点发送的停止任务请求 | EN Stop task request sent by master node to slave node
type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlaveId       string                 `protobuf:"bytes,1,opt,name=slave_id,json=slaveId,proto3" json:"slave_id,omitempty"` // 从节点 ID | EN Slave node ID
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`    // 要停止的任务 ID | EN ID of the task to stop
	Force         bool                   `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`                   // 是否强制停止（忽略任务状态，直接终止） | EN Whether to force stop (ignore task state and terminate directly)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_stress_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stress_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_stress_proto_rawDescGZIP(), []int{6}
}

func (x *StopRequest) GetSlaveId() string {
	if x != nil {
		return x.SlaveId
	}
	return ""
}

func (x *StopRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *StopRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// 停止响应 | EN Stop Response
// 从节点对停止任务请求的响应 | EN Slave node's response to stop task request
type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stopped       bool                   `protobuf:"varint,1,opt,name=stopped,proto3" json:"stopped,omitempty"` // 任务是否已停止 | EN Whether the task has been stopped
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 停止结果描述（失败时说明原因） | EN Description of stop result (explain reason if failed)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_stress_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stress_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_stress_proto_rawDescGZIP(), []int{7}
}

func (x *StopResponse) GetStopped() bool {
	if x != nil {
		return x.Stopped
	}
	return false
}

func (x *StopResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 状态请求 | EN Status Request
// 主节点查询从节点状态的请求参数 | EN Request parameters for master node to query slave node status
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlaveId       string                 `protobuf:"bytes,1,opt,name=slave_id,json=slaveId,proto3" json:"slave_id,omitempty"` // 要查询的从节点 ID | EN ID of the slave node to query
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_stress_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stress_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_stress_proto_rawDescGZIP(), []int{8}
}

func (x *StatusRequest) GetSlaveId() string {
	if x != nil {
		return x.SlaveId
	}
	return ""
}

// Slave 状态 | EN Slave Status
// 从节点的实时运行状态信息 | EN Real-time running status information of slave node
type SlaveStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SlaveId        string                 `protobuf:"bytes,1,opt,name=slave_id,json=slaveId,proto3" json:"slave_id,omitempty"`                       // 从节点 ID | EN Slave node ID
	State          AgentState             `protobuf:"varint,2,opt,name=state,proto3,enum=stress.AgentState" json:"state,omitempty"`                  // 从节点当前状态（枚举值） | EN Current state of slave node (enumeration value)
	CurrentTaskId  string                 `protobuf:"bytes,3,opt,name=current_task_id,json=currentTaskId,proto3" json:"current_task_id,omitempty"`   // 当前正在执行的任务 ID（无则为空） | EN ID of the currently executing task (empty if none)
	CpuUsage       float64                `protobuf:"fixed64,4,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`                  // CPU 使用率（0-100） | EN CPU usage rate (0-100)
	MemoryUsage    float64                `protobuf:"fixed64,5,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`         // 内存使用率（0-100） | EN Memory usage rate (0-100)
	RunningWorkers int64                  `protobuf:"varint,6,opt,name=running_workers,json=runningWorkers,proto3" json:"running_workers,omitempty"` // 当前运行的工作协程数 | EN Number of currently running worker goroutines
	TotalRequests  int64                  `protobuf:"varint,7,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`    // 已发送的总请求数 | EN Total number of requests sent
	Timestamp      int64                  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                 // 状态采集时间戳（毫秒） | EN Status collection timestamp (milliseconds)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SlaveStatus) Reset() {
	*x = SlaveStatus{}
	mi := &file_stress_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlaveStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlaveStatus) ProtoMessage() {}

func (x *SlaveStatus) ProtoReflect() protoreflect.Message {
	mi := &file_stress_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlaveStatus.ProtoReflect.Descriptor instead.
func (*SlaveStatus) Descriptor() ([]byte, []int) {
	return file_stress_proto_rawDescGZIP(), []int{9}
}

func (x *SlaveStatus) GetSlaveId() string {
	if x != nil {
		return x.SlaveId
	}
	return ""
}

func (x *SlaveStatus) GetState() AgentState {
	if x != nil {
		return x.State
	}
	return AgentState_AGENT_STATE_UNSPECIFIED
}

func (x *SlaveStatus) GetCurrentTaskId() string {
	if x != nil {
		return x.CurrentTaskId
	}
	return ""
}

func (x *SlaveStatus) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *SlaveStatus) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *SlaveStatus) GetRunningWorkers() int64 {
	if x != nil {
		return x.RunningWorkers
	}
	return 0
}

func (x *SlaveStatus) GetTotalRequests() int64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *SlaveStatus) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 统计数据 | EN Statistics Data
// 从节点上报的压测任务实时统计数据 | EN Real-time statistics data of stress test task reported by slave node
type StatsData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SlaveId         string                 `protobuf:"bytes,1,opt,name=slave_id,json=slaveId,proto3" json:"slave_id,omitempty"`                                                                                         // 从节点 ID | EN Slave node ID
	TaskId          string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                                                                                            // 任务 ID | EN Task ID
	Timestamp       int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                                                                   // 统计数据采集时间戳(毫秒) | EN Statistics collection timestamp (milliseconds)
	TotalRequests   int64                  `protobuf:"varint,4,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`                                                                      // 累计请求总数 | EN Total cumulative requests
	SuccessRequests int64                  `protobuf:"varint,5,opt,name=success_requests,json=successRequests,proto3" json:"success_requests,omitempty"`                                                                // 成功请求数 | EN Number of successful requests
	FailedRequests  int64                  `protobuf:"varint,6,opt,name=failed_requests,json=failedRequests,proto3" json:"failed_requests,omitempty"`                                                                   // 失败请求数 | EN Number of failed requests
	AvgLatency      float64                `protobuf:"fixed64,7,opt,name=avg_latency,json=avgLatency,proto3" json:"avg_latency,omitempty"`                                                                              // 平均响应延迟(毫秒) | EN Average response latency (milliseconds)
	P95Latency      float64                `protobuf:"fixed64,8,opt,name=p95_latency,json=p95Latency,proto3" json:"p95_latency,omitempty"`                                                                              // P95 响应延迟（毫秒）：95%的请求延迟小于该值 | EN P95 response latency (milliseconds): 95% of requests have latency less than this value
	P99Latency      float64                `protobuf:"fixed64,9,opt,name=p99_latency,json=p99Latency,proto3" json:"p99_latency,omitempty"`                                                                              // P99 响应延迟（毫秒）：99%的请求延迟小于该值 | EN P99 response latency (milliseconds): 99% of requests have latency less than this value
	MinLatency      float64                `protobuf:"fixed64,10,opt,name=min_latency,json=minLatency,proto3" json:"min_latency,omitempty"`                                                                             // 最小响应延迟（毫秒） | EN Minimum response latency (milliseconds)
	MaxLatency      float64                `protobuf:"fixed64,11,opt,name=max_latency,json=maxLatency,proto3" json:"max_latency,omitempty"`                                                                             // 最大响应延迟（毫秒） | EN Maximum response latency (milliseconds)
	Qps             float64                `protobuf:"fixed64,12,opt,name=qps,proto3" json:"qps,omitempty"`                                                                                                             // 每秒请求数（Queries Per Second） | EN Queries Per Second
	StatusCodes     map[string]int64       `protobuf:"bytes,13,rep,name=status_codes,json=statusCodes,proto3" json:"status_codes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // HTTP 状态码/GRPC 错误码计数（如 "200": 1000, "500": 50） | EN HTTP status code/GRPC error code count (e.g., "200": 1000, "500": 50)
	ErrorTypes      map[string]int64       `protobuf:"bytes,14,rep,name=error_types,json=errorTypes,proto3" json:"error_types,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`    // 错误类型计数（如 "timeout": 20, "connection_error": 10） | EN Error type count (e.g., "timeout": 20, "connection_error": 10)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StatsData) Reset() {
	*x = StatsData{}
	mi := &file_stress_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsData) ProtoMessage() {}

func (x *StatsData) ProtoReflect() protoreflect.Message {
	mi := &file_stress_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsData.ProtoReflect.Descriptor instead.
func (*StatsData) Descriptor() ([]byte, []int) {
	return file_stress_proto_rawDescGZIP(), []int{10}
}

func (x *StatsData) GetSlaveId() string {
	if x != nil {
		return x.SlaveId
	}
	return ""
}

func (x *StatsData) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *StatsData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *StatsData) GetTotalRequests() int64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *StatsData) GetSuccessRequests() int64 {
	if x != nil {
		return x.SuccessRequests
	}
	return 0
}

func (x *StatsData) GetFailedRequests() int64 {
	if x != nil {
		return x.FailedRequests
	}
	return 0
}

func (x *StatsData) GetAvgLatency() float64 {
	if x != nil {
		return x.AvgLatency
	}
	return 0
}

func (x *StatsData) GetP95Latency() float64 {
	if x != nil {
		return x.P95Latency
	}
	return 0
}

func (x *StatsData) GetP99Latency() float64 {
	if x != nil {
		return x.P99Latency
	}
	return 0
}

func (x *StatsData) GetMinLatency() float64 {
	if x != nil {
		return x.MinLatency
	}
	return 0
}

func (x *StatsData) GetMaxLatency() float64 {
	if x != nil {
		return x.MaxLatency
	}
	return 0
}

func (x *StatsData) GetQps() float64 {
	if x != nil {
		return x.Qps
	}
	return 0
}

func (x *StatsData) GetStatusCodes() map[string]int64 {
	if x != nil {
		return x.StatusCodes
	}
	return nil
}

func (x *StatsData) GetErrorTypes() map[string]int64 {
	if x != nil {
		return x.ErrorTypes
	}
	return nil
}

// 上报响应 | EN Report Response
// 主节点对统计数据上报的响应 | EN Master node's response to statistics reporting
type ReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      bool                   `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"` // 数据是否成功接收 | EN Whether data is received successfully
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`    // 接收结果描述 | EN Description of reception result
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResponse) Reset() {
	*x = ReportResponse{}
	mi := &file_stress_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResponse) ProtoMessage() {}

func (x *ReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stress_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResponse.ProtoReflect.Descriptor instead.
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return file_stress_proto_rawDescGZIP(), []int{11}
}

func (x *ReportResponse) GetReceived() bool {
	if x != nil {
		return x.Received
	}
	return false
}

func (x *ReportResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 任务完成请求 | EN Task Completion Request
// 从节点向主节点报告任务执行完成的请求参数 | EN Request parameters for slave node to report task execution completion to master node
type TaskCompletionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlaveId       string                 `protobuf:"bytes,1,opt,name=slave_id,json=slaveId,proto3" json:"slave_id,omitempty"`                // 从节点 ID | EN Slave node ID
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                   // 任务 ID | EN Task ID
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`                              // 任务是否成功完成 | EN Whether task completed successfully
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // 失败原因（仅在success=false时有效） | EN Failure reason (only valid when success=false)
	CompletedAt   int64                  `protobuf:"varint,5,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`   // 任务完成时间戳（毫秒） | EN Task completion timestamp (milliseconds)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskCompletionRequest) Reset() {
	*x = TaskCompletionRequest{}
	mi := &file_stress_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskCompletionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskCompletionRequest) ProtoMessage() {}

func (x *TaskCompletionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stress_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskCompletionRequest.ProtoReflect.Descriptor instead.
func (*TaskCompletionRequest) Descriptor() ([]byte, []int) {
	return file_stress_proto_rawDescGZIP(), []int{12}
}

func (x *TaskCompletionRequest) GetSlaveId() string {
	if x != nil {
		return x.SlaveId
	}
	return ""
}

func (x *TaskCompletionRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskCompletionRequest) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskCompletionRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TaskCompletionRequest) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

// 任务完成响应 | EN Task Completion Response
// 主节点对任务完成通知的响应 | EN Master node's response to task completion notification
type TaskCompletionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"` // 是否确认接收 | EN Whether receipt is acknowledged
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`            // 响应描述信息 | EN Response description information
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskCompletionResponse) Reset() {
	*x = TaskCompletionResponse{}
	mi := &file_stress_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskCompletionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskCompletionResponse) ProtoMessage() {}

func (x *TaskCompletionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stress_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskCompletionResponse.ProtoReflect.Descriptor instead.
func (*TaskCompletionResponse) Descriptor() ([]byte, []int) {
	return file_stress_proto_rawDescGZIP(), []int{13}
}

func (x *TaskCompletionResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *TaskCompletionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 下线请求 | EN Unregister Request
// 从节点向主节点发起的下线请求参数 | EN Parameters for slave node to initiate unregistration request to master node
type UnregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlaveId       string                 `protobuf:"bytes,1,opt,name=slave_id,json=slaveId,proto3" json:"slave_id,omitempty"` // 从节点 ID | EN Slave node ID
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`                  // 下线原因（如 "正常退出"、"系统升级"） | EN Unregistration reason (e.g., "normal exit", "system upgrade")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterRequest) Reset() {
	*x = UnregisterRequest{}
	mi := &file_stress_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterRequest) ProtoMessage() {}

func (x *UnregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stress_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterRequest.ProtoReflect.Descriptor instead.
func (*UnregisterRequest) Descriptor() ([]byte, []int) {
	return file_stress_proto_rawDescGZIP(), []int{14}
}

func (x *UnregisterRequest) GetSlaveId() string {
	if x != nil {
		return x.SlaveId
	}
	return ""
}

func (x *UnregisterRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// 下线响应 | EN Unregister Response
// 主节点对下线请求的响应 | EN Master node's response to unregistration request
type UnregisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 下线是否成功 | EN Whether unregistration is successful
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 下线结果描述 | EN Description of unregistration result
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterResponse) Reset() {
	*x = UnregisterResponse{}
	mi := &file_stress_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterResponse) ProtoMessage() {}

func (x *UnregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stress_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterResponse.ProtoReflect.Descriptor instead.
func (*UnregisterResponse) Descriptor() ([]byte, []int) {
	return file_stress_proto_rawDescGZIP(), []int{15}
}

func (x *UnregisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnregisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 配置更新 | EN Configuration Update
// 主节点向从节点下发的配置更新请求 | EN Configuration update request sent by master node to slave node
type ConfigUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlaveId       string                 `protobuf:"bytes,1,opt,name=slave_id,json=slaveId,proto3" json:"slave_id,omitempty"`                                                          // 从节点 ID | EN Slave node ID
	Config        map[string]string      `protobuf:"bytes,2,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 键值对形式的配置项（如 "max_workers": "1000"） | EN Key-value configuration items (e.g., "max_workers": "1000")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigUpdate) Reset() {
	*x = ConfigUpdate{}
	mi := &file_stress_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigUpdate) ProtoMessage() {}

func (x *ConfigUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_stress_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigUpdate.ProtoReflect.Descriptor instead.
func (*ConfigUpdate) Descriptor() ([]byte, []int) {
	return file_stress_proto_rawDescGZIP(), []int{16}
}

func (x *ConfigUpdate) GetSlaveId() string {
	if x != nil {
		return x.SlaveId
	}
	return ""
}

func (x *ConfigUpdate) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

// 更新响应 | EN Update Response
// 从节点对配置更新请求的响应 | EN Slave node's response to configuration update request
type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 配置更新是否成功 | EN Whether configuration update is successful
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 更新结果描述（失败时说明原因） | EN Description of update result (explain reason if failed)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_stress_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stress_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_stress_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 详情查询请求 | EN Details Query Request
// 主节点查询从节点请求详情的请求参数 | EN Request parameters for master node to query slave node request details
type DetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlaveId       string                 `protobuf:"bytes,1,opt,name=slave_id,json=slaveId,proto3" json:"slave_id,omitempty"` // 从节点 ID | EN Slave node ID
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`    // 任务 ID | EN Task ID
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`                 // 分页偏移量（从0开始） | EN Pagination offset (starting from 0)
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`                   // 每页数量（最大1000） | EN Number of items per page (max 1000)
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`                  // 状态过滤：all | success | failed | skipped | EN Status filter: all | success | failed | skipped
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetailsRequest) Reset() {
	*x = DetailsRequest{}
	mi := &file_stress_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailsRequest) ProtoMessage() {}

func (x *DetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stress_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailsRequest.ProtoReflect.Descriptor instead.
func (*DetailsRequest) Descriptor() ([]byte, []int) {
	return file_stress_proto_rawDescGZIP(), []int{18}
}

func (x *DetailsRequest) GetSlaveId() string {
	if x != nil {
		return x.SlaveId
	}
	return ""
}

func (x *DetailsRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *DetailsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *DetailsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *DetailsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// 请求详情 | EN Request Detail
// 单个请求的详细信息 | EN Detailed information of a single request
type RequestDetail struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                                                             // 详情记录 ID | EN Detail record ID
	SlaveId         string                 `protobuf:"bytes,2,opt,name=slave_id,json=slaveId,proto3" json:"slave_id,omitempty"`                                                                                                    // 从节点 ID | EN Slave node ID
	TaskId          string                 `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                                                                                                       // 任务 ID | EN Task ID
	Timestamp       int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                                                                              // 请求时间戳（Unix毫秒） | EN Request timestamp (Unix milliseconds)
	Duration        int64                  `protobuf:"varint,5,opt,name=duration,proto3" json:"duration,omitempty"`                                                                                                                // 响应时长（纳秒） | EN Response duration (nanoseconds)
	StatusCode      int32                  `protobuf:"varint,6,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`                                                                                          // 响应状态码 | EN Response status code
	Success         bool                   `protobuf:"varint,7,opt,name=success,proto3" json:"success,omitempty"`                                                                                                                  // 是否成功 | EN Whether successful
	Skipped         bool                   `protobuf:"varint,8,opt,name=skipped,proto3" json:"skipped,omitempty"`                                                                                                                  // 是否跳过 | EN Whether skipped
	SkipReason      string                 `protobuf:"bytes,9,opt,name=skip_reason,json=skipReason,proto3" json:"skip_reason,omitempty"`                                                                                           // 跳过原因 | EN Skip reason
	GroupId         uint64                 `protobuf:"varint,10,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`                                                                                                  // 分组 ID | EN Group ID
	ApiName         string                 `protobuf:"bytes,11,opt,name=api_name,json=apiName,proto3" json:"api_name,omitempty"`                                                                                                   // API 名称 | EN API name
	Error           string                 `protobuf:"bytes,12,opt,name=error,proto3" json:"error,omitempty"`                                                                                                                      // 错误信息 | EN Error message
	Size            float64                `protobuf:"fixed64,13,opt,name=size,proto3" json:"size,omitempty"`                                                                                                                      // 响应大小 | EN Response size
	Url             string                 `protobuf:"bytes,14,opt,name=url,proto3" json:"url,omitempty"`                                                                                                                          // 请求 URL | EN Request URL
	Method          string                 `protobuf:"bytes,15,opt,name=method,proto3" json:"method,omitempty"`                                                                                                                    // 请求方法 | EN Request method
	Query           string                 `protobuf:"bytes,16,opt,name=query,proto3" json:"query,omitempty"`                                                                                                                      // Query 参数 | EN Query parameters
	Headers         map[string]string      `protobuf:"bytes,17,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`                                        // 请求头 | EN Request headers
	Body            string                 `protobuf:"bytes,18,opt,name=body,proto3" json:"body,omitempty"`                                                                                                                        // 请求体 | EN Request body
	ResponseBody    string                 `protobuf:"bytes,19,opt,name=response_body,json=responseBody,proto3" json:"response_body,omitempty"`                                                                                    // 响应体 | EN Response body
	ResponseHeaders map[string]string      `protobuf:"bytes,20,rep,name=response_headers,json=responseHeaders,proto3" json:"response_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 响应头 | EN Response headers
	ExtractedVars   map[string]string      `protobuf:"bytes,21,rep,name=extracted_vars,json=extractedVars,proto3" json:"extracted_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`       // 提取的变量 | EN Extracted variables
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RequestDetail) Reset() {
	*x = RequestDetail{}
	mi := &file_stress_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDetail) ProtoMessage() {}

func (x *RequestDetail) ProtoReflect() protoreflect.Message {
	mi := &file_stress_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDetail.ProtoReflect.Descriptor instead.
func (*RequestDetail) Descriptor() ([]byte, []int) {
	return file_stress_proto_rawDescGZIP(), []int{19}
}

func (x *RequestDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RequestDetail) GetSlaveId() string {
	if x != nil {
		return x.SlaveId
	}
	return ""
}

func (x *RequestDetail) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *RequestDetail) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *RequestDetail) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *RequestDetail) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *RequestDetail) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RequestDetail) GetSkipped() bool {
	if x != nil {
		return x.Skipped
	}
	return false
}

func (x *RequestDetail) GetSkipReason() string {
	if x != nil {
		return x.SkipReason
	}
	return ""
}

func (x *RequestDetail) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *RequestDetail) GetApiName() string {
	if x != nil {
		return x.ApiName
	}
	return ""
}

func (x *RequestDetail) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RequestDetail) GetSize() float64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *RequestDetail) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *RequestDetail) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RequestDetail) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RequestDetail) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *RequestDetail) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *RequestDetail) GetResponseBody() string {
	if x != nil {
		return x.ResponseBody
	}
	return ""
}

func (x *RequestDetail) GetResponseHeaders() map[string]string {
	if x != nil {
		return x.ResponseHeaders
	}
	return nil
}

func (x *RequestDetail) GetExtractedVars() map[string]string {
	if x != nil {
		return x.ExtractedVars
	}
	return nil
}

// 详情查询响应 | EN Details Query Response
// 从节点返回的请求详情列表 | EN List of request details returned by slave node
type DetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`                                      // 总记录数（满足过滤条件的） | EN Total number of records (matching filter conditions)
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`                                    // 当前偏移量 | EN Current offset
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                                      // 每页数量 | EN Number of items per page
	Details       []*RequestDetail       `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty"`                                   // 详情记录列表 | EN List of detail records
	TotalRequests int64                  `protobuf:"varint,5,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"` // 真实总请求数 | EN Real total number of requests
	SuccessCount  int64                  `protobuf:"varint,6,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`    // 真实成功数 | EN Real number of successful requests
	FailedCount   int64                  `protobuf:"varint,7,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`       // 真实失败数 | EN Real number of failed requests
	SkippedCount  int64                  `protobuf:"varint,8,opt,name=skipped_count,json=skippedCount,proto3" json:"skipped_count,omitempty"`    // 真实跳过数 | EN Real number of skipped requests
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetailsResponse) Reset() {
	*x = DetailsResponse{}
	mi := &file_stress_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailsResponse) ProtoMessage() {}

func (x *DetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stress_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailsResponse.ProtoReflect.Descriptor instead.
func (*DetailsResponse) Descriptor() ([]byte, []int) {
	return file_stress_proto_rawDescGZIP(), []int{20}
}

func (x *DetailsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *DetailsResponse) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *DetailsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *DetailsResponse) GetDetails() []*RequestDetail {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *DetailsResponse) GetTotalRequests() int64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *DetailsResponse) GetSuccessCount() int64 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *DetailsResponse) GetFailedCount() int64 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

func (x *DetailsResponse) GetSkippedCount() int64 {
	if x != nil {
		return x.SkippedCount
	}
	return 0
}

var File_stress_proto protoreflect.FileDescriptor

const file_stress_proto_rawDesc = "" +
	"\n" +
	"\fstress.proto\x12\x06stress\"\xc8\x02\n" +
	"\tSlaveInfo\x12\x19\n" +
	"\bslave_id\x18\x01 \x01(\tR\aslaveId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x12\x1b\n" +
	"\tcpu_cores\x18\x04 \x01(\x05R\bcpuCores\x12\x16\n" +
	"\x06memory\x18\x05 \x01(\x03R\x06memory\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\x12\x16\n" +
	"\x06region\x18\a \x01(\tR\x06region\x125\n" +
	"\x06labels\x18\b \x03(\v2\x1d.stress.SlaveInfo.LabelsEntryR\x06labels\x12\x1b\n" +
	"\tgrpc_port\x18\t \x01(\x05R\bgrpcPort\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8b\x01\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12-\n" +
	"\x12heartbeat_interval\x18\x04 \x01(\x03R\x11heartbeatInterval\"x\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bslave_id\x18\x01 \x01(\tR\aslaveId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12+\n" +
	"\x06status\x18\x03 \x01(\v2\x13.stress.SlaveStatusR\x06status\"Y\n" +
	"\x11HeartbeatResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1a\n" +
	"\bcommands\x18\x03 \x03(\tR\bcommands\"\xb6\x02\n" +
	"\n" +
	"TaskConfig\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12,\n" +
	"\bprotocol\x18\x02 \x01(\x0e2\x10.stress.ProtocolR\bprotocol\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12!\n" +
	"\fworker_count\x18\x04 \x01(\x05R\vworkerCount\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\x05R\bduration\x12\x17\n" +
	"\aramp_up\x18\x06 \x01(\x05R\x06rampUp\x12\x1f\n" +
	"\vconfig_data\x18\a \x01(\fR\n" +
	"configData\x12'\n" +
	"\x0freport_interval\x18\b \x01(\x05R\x0ereportInterval\x12'\n" +
	"\x05state\x18\t \x01(\x0e2\x11.stress.TaskStateR\x05state\"]\n" +
	"\fTaskResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\tR\x06taskId\"W\n" +
	"\vStopRequest\x12\x19\n" +
	"\bslave_id\x18\x01 \x01(\tR\aslaveId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05force\x18\x03 \x01(\bR\x05force\"B\n" +
	"\fStopResponse\x12\x18\n" +
	"\astopped\x18\x01 \x01(\bR\astopped\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"*\n" +
	"\rStatusRequest\x12\x19\n" +
	"\bslave_id\x18\x01 \x01(\tR\aslaveId\"\xa8\x02\n" +
	"\vSlaveStatus\x12\x19\n" +
	"\bslave_id\x18\x01 \x01(\tR\aslaveId\x12(\n" +
	"\x05state\x18\x02 \x01(\x0e2\x12.stress.AgentStateR\x05state\x12&\n" +
	"\x0fcurrent_task_id\x18\x03 \x01(\tR\rcurrentTaskId\x12\x1b\n" +
	"\tcpu_usage\x18\x04 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x05 \x01(\x01R\vmemoryUsage\x12'\n" +
	"\x0frunning_workers\x18\x06 \x01(\x03R\x0erunningWorkers\x12%\n" +
	"\x0etotal_requests\x18\a \x01(\x03R\rtotalRequests\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\"\x99\x05\n" +
	"\tStatsData\x12\x19\n" +
	"\bslave_id\x18\x01 \x01(\tR\aslaveId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12%\n" +
	"\x0etotal_requests\x18\x04 \x01(\x03R\rtotalRequests\x12)\n" +
	"\x10success_requests\x18\x05 \x01(\x03R\x0fsuccessRequests\x12'\n" +
	"\x0ffailed_requests\x18\x06 \x01(\x03R\x0efailedRequests\x12\x1f\n" +
	"\vavg_latency\x18\a \x01(\x01R\n" +
	"avgLatency\x12\x1f\n" +
	"\vp95_latency\x18\b \x01(\x01R\n" +
	"p95Latency\x12\x1f\n" +
	"\vp99_latency\x18\t \x01(\x01R\n" +
	"p99Latency\x12\x1f\n" +
	"\vmin_latency\x18\n" +
	" \x01(\x01R\n" +
	"minLatency\x12\x1f\n" +
	"\vmax_latency\x18\v \x01(\x01R\n" +
	"maxLatency\x12\x10\n" +
	"\x03qps\x18\f \x01(\x01R\x03qps\x12E\n" +
	"\fstatus_codes\x18\r \x03(\v2\".stress.StatsData.StatusCodesEntryR\vstatusCodes\x12B\n" +
	"\verror_types\x18\x0e \x03(\v2!.stress.StatsData.ErrorTypesEntryR\n" +
	"errorTypes\x1a>\n" +
	"\x10StatusCodesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a=\n" +
	"\x0fErrorTypesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"F\n" +
	"\x0eReportResponse\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\bR\breceived\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xad\x01\n" +
	"\x15TaskCompletionRequest\x12\x19\n" +
	"\bslave_id\x18\x01 \x01(\tR\aslaveId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12!\n" +
	"\fcompleted_at\x18\x05 \x01(\x03R\vcompletedAt\"V\n" +
	"\x16TaskCompletionResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"F\n" +
	"\x11UnregisterRequest\x12\x19\n" +
	"\bslave_id\x18\x01 \x01(\tR\aslaveId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"H\n" +
	"\x12UnregisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x9e\x01\n" +
	"\fConfigUpdate\x12\x19\n" +
	"\bslave_id\x18\x01 \x01(\tR\aslaveId\x128\n" +
	"\x06config\x18\x02 \x03(\v2 .stress.ConfigUpdate.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"D\n" +
	"\x0eUpdateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x8a\x01\n" +
	"\x0eDetailsRequest\x12\x19\n" +
	"\bslave_id\x18\x01 \x01(\tR\aslaveId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"\x84\a\n" +
	"\rRequestDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bslave_id\x18\x02 \x01(\tR\aslaveId\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\tR\x06taskId\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\x03R\bduration\x12\x1f\n" +
	"\vstatus_code\x18\x06 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\asuccess\x18\a \x01(\bR\asuccess\x12\x18\n" +
	"\askipped\x18\b \x01(\bR\askipped\x12\x1f\n" +
	"\vskip_reason\x18\t \x01(\tR\n" +
	"skipReason\x12\x19\n" +
	"\bgroup_id\x18\n" +
	" \x01(\x04R\agroupId\x12\x19\n" +
	"\bapi_name\x18\v \x01(\tR\aapiName\x12\x14\n" +
	"\x05error\x18\f \x01(\tR\x05error\x12\x12\n" +
	"\x04size\x18\r \x01(\x01R\x04size\x12\x10\n" +
	"\x03url\x18\x0e \x01(\tR\x03url\x12\x16\n" +
	"\x06method\x18\x0f \x01(\tR\x06method\x12\x14\n" +
	"\x05query\x18\x10 \x01(\tR\x05query\x12<\n" +
	"\aheaders\x18\x11 \x03(\v2\".stress.RequestDetail.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x12 \x01(\tR\x04body\x12#\n" +
	"\rresponse_body\x18\x13 \x01(\tR\fresponseBody\x12U\n" +
	"\x10response_headers\x18\x14 \x03(\v2*.stress.RequestDetail.ResponseHeadersEntryR\x0fresponseHeaders\x12O\n" +
	"\x0eextracted_vars\x18\x15 \x03(\v2(.stress.RequestDetail.ExtractedVarsEntryR\rextractedVars\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aB\n" +
	"\x14ResponseHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a@\n" +
	"\x12ExtractedVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9a\x02\n" +
	"\x0fDetailsResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12/\n" +
	"\adetails\x18\x04 \x03(\v2\x15.stress.RequestDetailR\adetails\x12%\n" +
	"\x0etotal_requests\x18\x05 \x01(\x03R\rtotalRequests\x12#\n" +
	"\rsuccess_count\x18\x06 \x01(\x03R\fsuccessCount\x12!\n" +
	"\ffailed_count\x18\a \x01(\x03R\vfailedCount\x12#\n" +
	"\rskipped_count\x18\b \x01(\x03R\fskippedCount*\xa2\x01\n" +
	"\n" +
	"AgentState\x12\x1b\n" +
	"\x17AGENT_STATE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10AGENT_STATE_IDLE\x10\x01\x12\x17\n" +
	"\x13AGENT_STATE_RUNNING\x10\x02\x12\x18\n" +
	"\x14AGENT_STATE_STOPPING\x10\x03\x12\x15\n" +
	"\x11AGENT_STATE_ERROR\x10\x04\x12\x17\n" +
	"\x13AGENT_STATE_OFFLINE\x10\x05*\xa0\x01\n" +
	"\tTaskState\x12\x1a\n" +
	"\x16TASK_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TASK_STATE_PENDING\x10\x01\x12\x16\n" +
	"\x12TASK_STATE_RUNNING\x10\x02\x12\x18\n" +
	"\x14TASK_STATE_COMPLETED\x10\x03\x12\x15\n" +
	"\x11TASK_STATE_FAILED\x10\x04\x12\x16\n" +
	"\x12TASK_STATE_STOPPED\x10\x05*b\n" +
	"\bProtocol\x12\x18\n" +
	"\x14PROTOCOL_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rPROTOCOL_HTTP\x10\x01\x12\x11\n" +
	"\rPROTOCOL_GRPC\x10\x02\x12\x16\n" +
	"\x12PROTOCOL_WEBSOCKET\x10\x032\xec\x02\n" +
	"\rMasterService\x12<\n" +
	"\rRegisterSlave\x12\x11.stress.SlaveInfo\x1a\x18.stress.RegisterResponse\x12@\n" +
	"\tHeartbeat\x12\x18.stress.HeartbeatRequest\x1a\x19.stress.HeartbeatResponse\x12:\n" +
	"\vReportStats\x12\x11.stress.StatsData\x1a\x16.stress.ReportResponse(\x01\x12U\n" +
	"\x14ReportTaskCompletion\x12\x1d.stress.TaskCompletionRequest\x1a\x1e.stress.TaskCompletionResponse\x12H\n" +
	"\x0fUnregisterSlave\x12\x19.stress.UnregisterRequest\x1a\x1a.stress.UnregisterResponse2\xbb\x02\n" +
	"\fSlaveService\x127\n" +
	"\vExecuteTask\x12\x12.stress.TaskConfig\x1a\x14.stress.TaskResponse\x125\n" +
	"\bStopTask\x12\x13.stress.StopRequest\x1a\x14.stress.StopResponse\x127\n" +
	"\tGetStatus\x12\x15.stress.StatusRequest\x1a\x13.stress.SlaveStatus\x12<\n" +
	"\fUpdateConfig\x12\x14.stress.ConfigUpdate\x1a\x16.stress.UpdateResponse\x12D\n" +
	"\x11GetRequestDetails\x12\x16.stress.DetailsRequest\x1a\x17.stress.DetailsResponseB7Z5github.com/kamalyes/go-stress/distributed/proto;protob\x06proto3"

var (
	file_stress_proto_rawDescOnce sync.Once
	file_stress_proto_rawDescData []byte
)

func file_stress_proto_rawDescGZIP() []byte {
	file_stress_proto_rawDescOnce.Do(func() {
		file_stress_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stress_proto_rawDesc), len(file_stress_proto_rawDesc)))
	})
	return file_stress_proto_rawDescData
}

var file_stress_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_stress_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_stress_proto_goTypes = []any{
	(AgentState)(0),                // 0: stress.AgentState
	(TaskState)(0),                 // 1: stress.TaskState
	(Protocol)(0),                  // 2: stress.Protocol
	(*SlaveInfo)(nil),              // 3: stress.SlaveInfo
	(*RegisterResponse)(nil),       // 4: stress.RegisterResponse
	(*HeartbeatRequest)(nil),       // 5: stress.HeartbeatRequest
	(*HeartbeatResponse)(nil),      // 6: stress.HeartbeatResponse
	(*TaskConfig)(nil),             // 7: stress.TaskConfig
	(*TaskResponse)(nil),           // 8: stress.TaskResponse
	(*StopRequest)(nil),            // 9: stress.StopRequest
	(*StopResponse)(nil),           // 10: stress.StopResponse
	(*StatusRequest)(nil),          // 11: stress.StatusRequest
	(*SlaveStatus)(nil),            // 12: stress.SlaveStatus
	(*StatsData)(nil),              // 13: stress.StatsData
	(*ReportResponse)(nil),         // 14: stress.ReportResponse
	(*TaskCompletionRequest)(nil),  // 15: stress.TaskCompletionRequest
	(*TaskCompletionResponse)(nil), // 16: stress.TaskCompletionResponse
	(*UnregisterRequest)(nil),      // 17: stress.UnregisterRequest
	(*UnregisterResponse)(nil),     // 18: stress.UnregisterResponse
	(*ConfigUpdate)(nil),           // 19: stress.ConfigUpdate
	(*UpdateResponse)(nil),         // 20: stress.UpdateResponse
	(*DetailsRequest)(nil),         // 21: stress.DetailsRequest
	(*RequestDetail)(nil),          // 22: stress.RequestDetail
	(*DetailsResponse)(nil),        // 23: stress.DetailsResponse
	nil,                            // 24: stress.SlaveInfo.LabelsEntry
	nil,                            // 25: stress.StatsData.StatusCodesEntry
	nil,                            // 26: stress.StatsData.ErrorTypesEntry
	nil,                            // 27: stress.ConfigUpdate.ConfigEntry
	nil,                            // 28: stress.RequestDetail.HeadersEntry
	nil,                            // 29: stress.RequestDetail.ResponseHeadersEntry
	nil,                            // 30: stress.RequestDetail.ExtractedVarsEntry
}
var file_stress_proto_depIdxs = []int32{
	24, // 0: stress.SlaveInfo.labels:type_name -> stress.SlaveInfo.LabelsEntry
	12, // 1: stress.HeartbeatRequest.status:type_name -> stress.SlaveStatus
	2,  // 2: stress.TaskConfig.protocol:type_name -> stress.Protocol
	1,  // 3: stress.TaskConfig.state:type_name -> stress.TaskState
	0,  // 4: stress.SlaveStatus.state:type_name -> stress.AgentState
	25, // 5: stress.StatsData.status_codes:type_name -> stress.StatsData.StatusCodesEntry
	26, // 6: stress.StatsData.error_types:type_name -> stress.StatsData.ErrorTypesEntry
	27, // 7: stress.ConfigUpdate.config:type_name -> stress.ConfigUpdate.ConfigEntry
	28, // 8: stress.RequestDetail.headers:type_name -> stress.RequestDetail.HeadersEntry
	29, // 9: stress.RequestDetail.response_headers:type_name -> stress.RequestDetail.ResponseHeadersEntry
	30, // 10: stress.RequestDetail.extracted_vars:type_name -> stress.RequestDetail.ExtractedVarsEntry
	22, // 11: stress.DetailsResponse.details:type_name -> stress.RequestDetail
	3,  // 12: stress.MasterService.RegisterSlave:input_type -> stress.SlaveInfo
	5,  // 13: stress.MasterService.Heartbeat:input_type -> stress.HeartbeatRequest
	13, // 14: stress.MasterService.ReportStats:input_type -> stress.StatsData
	15, // 15: stress.MasterService.ReportTaskCompletion:input_type -> stress.TaskCompletionRequest
	17, // 16: stress.MasterService.UnregisterSlave:input_type -> stress.UnregisterRequest
	7,  // 17: stress.SlaveService.ExecuteTask:input_type -> stress.TaskConfig
	9,  // 18: stress.SlaveService.StopTask:input_type -> stress.StopRequest
	11, // 19: stress.SlaveService.GetStatus:input_type -> stress.StatusRequest
	19, // 20: stress.SlaveService.UpdateConfig:input_type -> stress.ConfigUpdate
	21, // 21: stress.SlaveService.GetRequestDetails:input_type -> stress.DetailsRequest
	4,  // 22: stress.MasterService.RegisterSlave:output_type -> stress.RegisterResponse
	6,  // 23: stress.MasterService.Heartbeat:output_type -> stress.HeartbeatResponse
	14, // 24: stress.MasterService.ReportStats:output_type -> stress.ReportResponse
	16, // 25: stress.MasterService.ReportTaskCompletion:output_type -> stress.TaskCompletionResponse
	18, // 26: stress.MasterService.UnregisterSlave:output_type -> stress.UnregisterResponse
	8,  // 27: stress.SlaveService.ExecuteTask:output_type -> stress.TaskResponse
	10, // 28: stress.SlaveService.StopTask:output_type -> stress.StopResponse
	12, // 29: stress.SlaveService.GetStatus:output_type -> stress.SlaveStatus
	20, // 30: stress.SlaveService.UpdateConfig:output_type -> stress.UpdateResponse
	23, // 31: stress.SlaveService.GetRequestDetails:output_type -> stress.DetailsResponse
	22, // [22:32] is the sub-list for method output_type
	12, // [12:22] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_stress_proto_init() }
func file_stress_proto_init() {
	if File_stress_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stress_proto_rawDesc), len(file_stress_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_stress_proto_goTypes,
		DependencyIndexes: file_stress_proto_depIdxs,
		EnumInfos:         file_stress_proto_enumTypes,
		MessageInfos:      file_stress_proto_msgTypes,
	}.Build()
	File_stress_proto = out.File
	file_stress_proto_goTypes = nil
	file_stress_proto_depIdxs = nil
}
