// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.24.3
// source: stress.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MasterService_RegisterSlave_FullMethodName        = "/stress.MasterService/RegisterSlave"
	MasterService_Heartbeat_FullMethodName            = "/stress.MasterService/Heartbeat"
	MasterService_ReportStats_FullMethodName          = "/stress.MasterService/ReportStats"
	MasterService_ReportTaskCompletion_FullMethodName = "/stress.MasterService/ReportTaskCompletion"
	MasterService_UnregisterSlave_FullMethodName      = "/stress.MasterService/UnregisterSlave"
)

// MasterServiceClient is the client API for MasterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Master 服务接口 | EN Master Service Interface
// 主节点（Master）对外提供的 gRPC 服务，供从节点（Slave）调用 | EN gRPC service provided by master node for slave nodes to call
type MasterServiceClient interface {
	// Slave 注册 | EN Slave Registration
	// 从节点启动后向主节点注册自身信息，完成接入流程 | EN After startup, slave node registers its information with master node to complete access process
	RegisterSlave(ctx context.Context, in *SlaveInfo, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Slave 心跳 | EN Slave Heartbeat
	// 从节点定期向主节点发送心跳，汇报自身状态，保持连接 | EN Slave node sends heartbeat to master node periodically to report status and maintain connection
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// 上报统计数据（流式） | EN Report Statistics (Stream)
	// 从节点以流式方式向主节点上报压测统计数据（支持批量/实时上报） | EN Slave node reports stress test statistics to master node in streaming mode (supports batch/realtime reporting)
	ReportStats(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StatsData, ReportResponse], error)
	// 任务完成通知 | EN Task Completion Notification
	// 从节点在任务执行完成后通知主节点更新任务状态 | EN Slave node notifies master node to update task status after task execution completes
	ReportTaskCompletion(ctx context.Context, in *TaskCompletionRequest, opts ...grpc.CallOption) (*TaskCompletionResponse, error)
	// Slave 下线 | EN Slave Unregistration
	// 从节点主动向主节点发起下线请求，注销自身信息 | EN Slave node actively initiates unregistration request to master node to cancel its information
	UnregisterSlave(ctx context.Context, in *UnregisterRequest, opts ...grpc.CallOption) (*UnregisterResponse, error)
}

type masterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMasterServiceClient(cc grpc.ClientConnInterface) MasterServiceClient {
	return &masterServiceClient{cc}
}

func (c *masterServiceClient) RegisterSlave(ctx context.Context, in *SlaveInfo, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, MasterService_RegisterSlave_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, MasterService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterServiceClient) ReportStats(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StatsData, ReportResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MasterService_ServiceDesc.Streams[0], MasterService_ReportStats_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StatsData, ReportResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MasterService_ReportStatsClient = grpc.ClientStreamingClient[StatsData, ReportResponse]

func (c *masterServiceClient) ReportTaskCompletion(ctx context.Context, in *TaskCompletionRequest, opts ...grpc.CallOption) (*TaskCompletionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskCompletionResponse)
	err := c.cc.Invoke(ctx, MasterService_ReportTaskCompletion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterServiceClient) UnregisterSlave(ctx context.Context, in *UnregisterRequest, opts ...grpc.CallOption) (*UnregisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnregisterResponse)
	err := c.cc.Invoke(ctx, MasterService_UnregisterSlave_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MasterServiceServer is the server API for MasterService service.
// All implementations must embed UnimplementedMasterServiceServer
// for forward compatibility.
//
// Master 服务接口 | EN Master Service Interface
// 主节点（Master）对外提供的 gRPC 服务，供从节点（Slave）调用 | EN gRPC service provided by master node for slave nodes to call
type MasterServiceServer interface {
	// Slave 注册 | EN Slave Registration
	// 从节点启动后向主节点注册自身信息，完成接入流程 | EN After startup, slave node registers its information with master node to complete access process
	RegisterSlave(context.Context, *SlaveInfo) (*RegisterResponse, error)
	// Slave 心跳 | EN Slave Heartbeat
	// 从节点定期向主节点发送心跳，汇报自身状态，保持连接 | EN Slave node sends heartbeat to master node periodically to report status and maintain connection
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// 上报统计数据（流式） | EN Report Statistics (Stream)
	// 从节点以流式方式向主节点上报压测统计数据（支持批量/实时上报） | EN Slave node reports stress test statistics to master node in streaming mode (supports batch/realtime reporting)
	ReportStats(grpc.ClientStreamingServer[StatsData, ReportResponse]) error
	// 任务完成通知 | EN Task Completion Notification
	// 从节点在任务执行完成后通知主节点更新任务状态 | EN Slave node notifies master node to update task status after task execution completes
	ReportTaskCompletion(context.Context, *TaskCompletionRequest) (*TaskCompletionResponse, error)
	// Slave 下线 | EN Slave Unregistration
	// 从节点主动向主节点发起下线请求，注销自身信息 | EN Slave node actively initiates unregistration request to master node to cancel its information
	UnregisterSlave(context.Context, *UnregisterRequest) (*UnregisterResponse, error)
	mustEmbedUnimplementedMasterServiceServer()
}

// UnimplementedMasterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMasterServiceServer struct{}

func (UnimplementedMasterServiceServer) RegisterSlave(context.Context, *SlaveInfo) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterSlave not implemented")
}
func (UnimplementedMasterServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedMasterServiceServer) ReportStats(grpc.ClientStreamingServer[StatsData, ReportResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ReportStats not implemented")
}
func (UnimplementedMasterServiceServer) ReportTaskCompletion(context.Context, *TaskCompletionRequest) (*TaskCompletionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportTaskCompletion not implemented")
}
func (UnimplementedMasterServiceServer) UnregisterSlave(context.Context, *UnregisterRequest) (*UnregisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterSlave not implemented")
}
func (UnimplementedMasterServiceServer) mustEmbedUnimplementedMasterServiceServer() {}
func (UnimplementedMasterServiceServer) testEmbeddedByValue()                       {}

// UnsafeMasterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MasterServiceServer will
// result in compilation errors.
type UnsafeMasterServiceServer interface {
	mustEmbedUnimplementedMasterServiceServer()
}

func RegisterMasterServiceServer(s grpc.ServiceRegistrar, srv MasterServiceServer) {
	// If the following call pancis, it indicates UnimplementedMasterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MasterService_ServiceDesc, srv)
}

func _MasterService_RegisterSlave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SlaveInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServiceServer).RegisterSlave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterService_RegisterSlave_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServiceServer).RegisterSlave(ctx, req.(*SlaveInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterService_ReportStats_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MasterServiceServer).ReportStats(&grpc.GenericServerStream[StatsData, ReportResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MasterService_ReportStatsServer = grpc.ClientStreamingServer[StatsData, ReportResponse]

func _MasterService_ReportTaskCompletion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskCompletionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServiceServer).ReportTaskCompletion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterService_ReportTaskCompletion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServiceServer).ReportTaskCompletion(ctx, req.(*TaskCompletionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterService_UnregisterSlave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServiceServer).UnregisterSlave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterService_UnregisterSlave_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServiceServer).UnregisterSlave(ctx, req.(*UnregisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MasterService_ServiceDesc is the grpc.ServiceDesc for MasterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MasterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stress.MasterService",
	HandlerType: (*MasterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterSlave",
			Handler:    _MasterService_RegisterSlave_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _MasterService_Heartbeat_Handler,
		},
		{
			MethodName: "ReportTaskCompletion",
			Handler:    _MasterService_ReportTaskCompletion_Handler,
		},
		{
			MethodName: "UnregisterSlave",
			Handler:    _MasterService_UnregisterSlave_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReportStats",
			Handler:       _MasterService_ReportStats_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "stress.proto",
}

const (
	SlaveService_ExecuteTask_FullMethodName       = "/stress.SlaveService/ExecuteTask"
	SlaveService_StopTask_FullMethodName          = "/stress.SlaveService/StopTask"
	SlaveService_GetStatus_FullMethodName         = "/stress.SlaveService/GetStatus"
	SlaveService_UpdateConfig_FullMethodName      = "/stress.SlaveService/UpdateConfig"
	SlaveService_GetRequestDetails_FullMethodName = "/stress.SlaveService/GetRequestDetails"
)

// SlaveServiceClient is the client API for SlaveService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Slave 服务接口 | EN Slave Service Interface
// 从节点（Slave）对外提供的 gRPC 服务，供主节点调用 | EN gRPC service provided by slave node for master node to call
type SlaveServiceClient interface {
	// 接收任务 | EN Receive Task
	// 主节点向从节点下发压测任务配置，触发任务执行 | EN Master node sends stress test task configuration to slave node to trigger task execution
	ExecuteTask(ctx context.Context, in *TaskConfig, opts ...grpc.CallOption) (*TaskResponse, error)
	// 停止任务 | EN Stop Task
	// 主节点指令从节点停止指定的压测任务 | EN Master node instructs slave node to stop the specified stress test task
	StopTask(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
	// 查询状态 | EN Query Status
	// 主节点查询从节点的当前运行状态 | EN Master node queries the current running status of slave node
	GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*SlaveStatus, error)
	// 更新配置 | EN Update Configuration
	// 主节点向从节点下发配置更新指令（如修改系统参数） | EN Master node sends configuration update instructions to slave node (e.g., modify system parameters)
	UpdateConfig(ctx context.Context, in *ConfigUpdate, opts ...grpc.CallOption) (*UpdateResponse, error)
	// 查询请求详情 | EN Query Request Details
	// 主节点查询从节点的请求详情数据（支持分页和状态过滤） | EN Master node queries request details from slave node (supports pagination and status filtering)
	GetRequestDetails(ctx context.Context, in *DetailsRequest, opts ...grpc.CallOption) (*DetailsResponse, error)
}

type slaveServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSlaveServiceClient(cc grpc.ClientConnInterface) SlaveServiceClient {
	return &slaveServiceClient{cc}
}

func (c *slaveServiceClient) ExecuteTask(ctx context.Context, in *TaskConfig, opts ...grpc.CallOption) (*TaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, SlaveService_ExecuteTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slaveServiceClient) StopTask(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, SlaveService_StopTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slaveServiceClient) GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*SlaveStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SlaveStatus)
	err := c.cc.Invoke(ctx, SlaveService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slaveServiceClient) UpdateConfig(ctx context.Context, in *ConfigUpdate, opts ...grpc.CallOption) (*UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, SlaveService_UpdateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slaveServiceClient) GetRequestDetails(ctx context.Context, in *DetailsRequest, opts ...grpc.CallOption) (*DetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetailsResponse)
	err := c.cc.Invoke(ctx, SlaveService_GetRequestDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SlaveServiceServer is the server API for SlaveService service.
// All implementations must embed UnimplementedSlaveServiceServer
// for forward compatibility.
//
// Slave 服务接口 | EN Slave Service Interface
// 从节点（Slave）对外提供的 gRPC 服务，供主节点调用 | EN gRPC service provided by slave node for master node to call
type SlaveServiceServer interface {
	// 接收任务 | EN Receive Task
	// 主节点向从节点下发压测任务配置，触发任务执行 | EN Master node sends stress test task configuration to slave node to trigger task execution
	ExecuteTask(context.Context, *TaskConfig) (*TaskResponse, error)
	// 停止任务 | EN Stop Task
	// 主节点指令从节点停止指定的压测任务 | EN Master node instructs slave node to stop the specified stress test task
	StopTask(context.Context, *StopRequest) (*StopResponse, error)
	// 查询状态 | EN Query Status
	// 主节点查询从节点的当前运行状态 | EN Master node queries the current running status of slave node
	GetStatus(context.Context, *StatusRequest) (*SlaveStatus, error)
	// 更新配置 | EN Update Configuration
	// 主节点向从节点下发配置更新指令（如修改系统参数） | EN Master node sends configuration update instructions to slave node (e.g., modify system parameters)
	UpdateConfig(context.Context, *ConfigUpdate) (*UpdateResponse, error)
	// 查询请求详情 | EN Query Request Details
	// 主节点查询从节点的请求详情数据（支持分页和状态过滤） | EN Master node queries request details from slave node (supports pagination and status filtering)
	GetRequestDetails(context.Context, *DetailsRequest) (*DetailsResponse, error)
	mustEmbedUnimplementedSlaveServiceServer()
}

// UnimplementedSlaveServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSlaveServiceServer struct{}

func (UnimplementedSlaveServiceServer) ExecuteTask(context.Context, *TaskConfig) (*TaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteTask not implemented")
}
func (UnimplementedSlaveServiceServer) StopTask(context.Context, *StopRequest) (*StopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopTask not implemented")
}
func (UnimplementedSlaveServiceServer) GetStatus(context.Context, *StatusRequest) (*SlaveStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedSlaveServiceServer) UpdateConfig(context.Context, *ConfigUpdate) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateConfig not implemented")
}
func (UnimplementedSlaveServiceServer) GetRequestDetails(context.Context, *DetailsRequest) (*DetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRequestDetails not implemented")
}
func (UnimplementedSlaveServiceServer) mustEmbedUnimplementedSlaveServiceServer() {}
func (UnimplementedSlaveServiceServer) testEmbeddedByValue()                      {}

// UnsafeSlaveServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SlaveServiceServer will
// result in compilation errors.
type UnsafeSlaveServiceServer interface {
	mustEmbedUnimplementedSlaveServiceServer()
}

func RegisterSlaveServiceServer(s grpc.ServiceRegistrar, srv SlaveServiceServer) {
	// If the following call pancis, it indicates UnimplementedSlaveServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SlaveService_ServiceDesc, srv)
}

func _SlaveService_ExecuteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlaveServiceServer).ExecuteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SlaveService_ExecuteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlaveServiceServer).ExecuteTask(ctx, req.(*TaskConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _SlaveService_StopTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlaveServiceServer).StopTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SlaveService_StopTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlaveServiceServer).StopTask(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SlaveService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlaveServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SlaveService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlaveServiceServer).GetStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SlaveService_UpdateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlaveServiceServer).UpdateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SlaveService_UpdateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlaveServiceServer).UpdateConfig(ctx, req.(*ConfigUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _SlaveService_GetRequestDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlaveServiceServer).GetRequestDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SlaveService_GetRequestDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlaveServiceServer).GetRequestDetails(ctx, req.(*DetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SlaveService_ServiceDesc is the grpc.ServiceDesc for SlaveService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SlaveService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stress.SlaveService",
	HandlerType: (*SlaveServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteTask",
			Handler:    _SlaveService_ExecuteTask_Handler,
		},
		{
			MethodName: "StopTask",
			Handler:    _SlaveService_StopTask_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _SlaveService_GetStatus_Handler,
		},
		{
			MethodName: "UpdateConfig",
			Handler:    _SlaveService_UpdateConfig_Handler,
		},
		{
			MethodName: "GetRequestDetails",
			Handler:    _SlaveService_GetRequestDetails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stress.proto",
}
